let lessons = [{
    id: 1,
        subject: 'Biology',
        location: 'Birmingham',
        price: 500,
        spaces: 5,
    },
    {
        id: 2,
        subject: 'English',
        location: 'London',
        price: 1500,
        spaces: 5,
    },
    {
        id: 3,
        subject: 'Mathematics',
        location: 'United Kingdom',
        price: 2500,
        spaces: 5,
    },
    {
        id: 4,
        subject: 'Chemistry',
        location: 'France',
        price: 3500,
        spaces: 5,
    },
    {
        id: 5,
        subject: 'Technical Drawing',
        location: 'Russia',
        price: 4500,
        spaces: 5,
    },
    {
        id: 6,
        subject: 'Biology',
        location: 'Birmingham',
        price: 500,
        spaces: 5,
    },
    {
        id: 7,
        subject: 'English',
        location: 'London',
        price: 1500,
        spaces: 5,
    },
    {
        id: 8,
        subject: 'Mathematics',
        location: 'United Kingdom',
        price: 2500,
        spaces: 5,
    },
    {
        id: 9,
        subject: 'Chemistry',
        location: 'France',
        price: 3500,
        spaces: 5,
    },
    {
        id: 10,
        subject: 'Technical Drawing',
        location: 'Russia',
        price: 4500,
        spaces: 5,
    }
]