let lessons = [{
        id: 1,
        subject: 'Biology',
        location: 'Birmingham',
        price: 500,
        spaces: 5,
    },
    {
        id: 2,
        subject: 'English',
        location: 'London',
        price: 1500,
        spaces: 5,
    },
    {
        id: 3,
        subject: 'Mathematics',
        location: 'United Kingdom',
        price: 2500,
        spaces: 5,
    },
    {
        id: 4,
        subject: 'Chemistry',
        location: 'France',
        price: 3500,
        spaces: 5,
    },
    {
        id: 5,
        subject: 'TD',
        location: 'Russia',
        price: 4500,
        spaces: 5,
    },
    {
        id: 6,
        subject: 'French',
        location: 'Dubai',
        price: 5500,
        spaces: 5,
    },
    {
        id: 7,
        subject: 'Yoruba',
        location: 'Nigeria',
        price: 6500,
        spaces: 5,
    },
    {
        id: 8,
        subject: 'Igbo',
        location: 'South Africa',
        price: 7500,
        spaces: 5,
    },
    {
        id: 9,
        subject: 'CRS',
        location: 'Poland',
        price: 8500,
        spaces: 5,
    },
    {
        id: 10,
        subject: 'Economics',
        location: 'Ireland',
        price: 9500,
        spaces: 5,
    }
]